CREATE TABLE service_security.major_com
(
order_id bigint COMMENT'订单ID',
driver_id bigint COMMENT'司机ID',
passenger_id   bigint COMMENT'乘客id',
city_id    int  COMMENT'城市ID',
city_name  string COMMENT'城市名',
birth_time   string COMMENT'订单产生时间',
starting_name  string COMMENT'订单起点名称',
dest_name  string COMMENT'订单终点名称 ',
start_dest_distance  int COMMENT'起点到终点距离',
normal_distance   double COMMENT'实际正常行驶距离',
arrive_time  string COMMENT'司机到达时间',
finish_time  string COMMENT'订单完成时间',
call_times   int COMMENT'呼叫次数',
begin_charge_time  string COMMENT'司机点击开始计费的时间',
product_id   int COMMENT'1专车 2企业 3快车',
will_pay   double COMMENT'乘客应付',
starting_lng   double COMMENT'起点经度',
starting_lat   double COMMENT'起点维度',
dest_lng   double COMMENT'终点经度',
dest_lat   double COMMENT'终点维度',
dynamic    int COMMENT'是否动态调价',
dynamic_price  double COMMENT'调价(元)',
combo_type   int COMMENT'订单类型',
driver_start_distance double COMMENT'司机与出发地的路面距离',
forecast_time  double COMMENT'出发地到目的地驾驶预估时间(单位:分钟)',
pre_total_fee  double COMMENT'预估价格',
order_status   int COMMENT'订单状态',
complete_type  int COMMENT'已经改派',
input    int COMMENT'输入',
is_new   int COMMENT'是否新用户的第一次下单',
date_type  int COMMENT'周几',
source_type  int COMMENT'订单来源',
real_time double COMMENT'订单实际计费时长(分)',
total_recerivetime   int COMMENT'接驾总时长(分)',
driver_wait_time   double COMMENT'司机等待时间(分)',
passenge_wait_time   double COMMENT'乘客等待时间(分)',
type     int COMMENT'订单类型：预约|实时|等等',
start_catalog  string COMMENT'开始地址的位置分类',
dest_catalog   string COMMENT'目标地址的位置分类',
d_age    int COMMENT'司机年龄',
d_gender   tinyint   COMMENT'性别',
d_create_time  string COMMENT'录入时间',
car_level  string COMMENT'车况级别',
d_phone_model  int COMMENT'手机型号',
d_type   tinyint   COMMENT'司机类型1:加盟司机2:自营车司机3:营运司机',
d_car_brand  string COMMENT'车辆品牌',
d_car_level  int COMMENT'车辆级别',
d_channel  int COMMENT'渠道',
d_work_times   double COMMENT'入职时长_月',
d_active_degree int COMMENT'活跃度',
d_complete_app string COMMENT'竞品APP',
d_finish_count int COMMENT'累计完成订单数',
d_total_passenger_complaint int COMMENT'累计被投诉次数',
d_total_driver_complaint INT COMMENT'累计投诉乘客次数',
d_work_day   int COMMENT'入职天数',
d_active_day   int COMMENT'上线天数',
d_average_level double COMMENT'司机最近100单的平均星级',
d_star_level   double COMMENT'司机星级',
d_low_star_ratio   double     COMMENT'低星级率',
d_cancle_rate   double   COMMENT'订单取消率',
d_tousulv    double   COMMENT'总被投诉率',
d_service_score double COMMENT'司机服务分，100分',
d_punish_num       int   COMMENT'司机封禁信息',
d_one_star_orders   int COMMENT'司机1星评论订单数',
d_two_star_orders   int COMMENT'司机2星评论订单数',
d_three_star_orders int COMMENT '司机3星评论订单数',
d_four_star_orders  int COMMENT '司机4星评论订单数',
d_five_star_orders  int COMMENT '司机5星评论订单数',
p_age   int COMMENT'乘客年龄',
p_gender  int COMMENT'乘客性别',
p_phone_model  string COMMENT'乘客端',
p_finish_count int COMMENT'完成订单数',
p_star_level   double COMMENT'总评分',
p_finish_num1w int COMMENT'最近1周订单数',
p_one_star_level_num int COMMENT'1星评论订单数',
p_two_star_level_num int COMMENT'2星评论订单数',
p_three_star_level_num int COMMENT'3星评论订单数',
p_four_star_level_num int COMMENT'4星评论订单数',
p_five_star_level_num int COMMENT'5星评论订单数',
p_phone_complaint_num int COMMENT'乘客电话投诉快车订单数',
p_app_complaint_num INT COMMENT'乘客app投诉快车订单数',
p_registered_time  int COMMENT'乘客注册年龄',
p_complaint_orders   int COMMENT'乘客投诉订单一天前',
p_complaint_by_driver int COMMENT'乘客被投诉一天前',
p_total_cancel_orders int COMMENT'乘客取消订单一天前',
p_night_peak   double COMMENT'夜间倾向',
p_complaint_orders_all int COMMENT'乘客投诉订单总量',
p_complaint_by_driver_all int COMMENT'乘客被投诉总量',
p_cancel_after_count int COMMENT '乘客取消订单总量',
complaint_result  int COMMENT'投诉结果',
valid   int COMMENT'是否有效',
path    string COMMENT'投诉内容分类路径',
product_type   int COMMENT'订单类型，1.专车， 2.企业专车,3.快车，4.企业快车',
content    string COMMENT'投诉说明',
deal_status  int COMMENT'工单处理状态,1.未处理，2进行中，3.完成',
business_type  int COMMENT'客户业务类型,1专车,2打车',
driver_passenger_complaint int COMMENT'是否司乘互投，0代表不是，1代表是司乘互投',
complaint_type int COMMENT'1表示乘客投诉司机，2表示司机投诉乘客',
customer_type int
)
PARTITIONED BY (
  `year` string,
  `month` string,
  `day` string)
LOCATION
  'hdfs://mycluster-tj/user/common_plat_security/data/service_security/major_com';