Create table  service_security.redup_normal_info_bak
(
order_id            bigint              COMMENT'订单ID',
driver_id           bigint              COMMENT'司机ID',
passenger_id        bigint              COMMENT'乘客id',
city_id             int                 COMMENT'城市ID',
city_name           string              COMMENT'城市名',
birth_time          string              COMMENT'订单产生时间',
starting_name       string              COMMENT'订单起点名称',
dest_name           string              COMMENT'订单终点名称',
start_dest_distance int                 COMMENT'起点到终点距离',
normal_distance     double              COMMENT'实际正常行驶距离',
arrive_time         string              COMMENT'司机到达时间',
finish_time         string              COMMENT'订单完成时间',
call_times          int                 COMMENT'呼叫次数',
begin_charge_time   string              COMMENT'司机点击开始计费的时间',
product_id          int                 COMMENT'1专车 2企业 3快车',
will_pay            double              COMMENT'乘客应付',
starting_lng        double              COMMENT'起点经度',
starting_lat        double              COMMENT'起点维度',
dest_lng            double              COMMENT'终点经度',
dest_lat            double              COMMENT'终点维度' ,
dynamic             int                 COMMENT'是否动态调价',
dynamic_price       double              COMMENT'调价(元)',
combo_type          int                 COMMENT'订单类型',
driver_start_distance double              COMMENT'司机与出发地的路面距离',
forecast_time       double              COMMENT'出发地到目的地驾驶预估时间(单位:分钟)',
pre_total_fee       double              COMMENT'预估价格',
order_status        int                 COMMENT'订单状态',
complete_type       int                 COMMENT'7已经改派',
input               int                 COMMENT'输入',
is_new              int                 COMMENT'是否新用户的第一次下单',
date_type           int                 COMMENT'周几',
source_type         int                 COMMENT'订单来源',
real_time           double              COMMENT'订单实际计费时长(分)',
total_recerivetime  int                 COMMENT'接驾总时长(分)',
driver_wait_time    double              COMMENT'司机等待时间(分)',
passenge_wait_time  double              COMMENT'乘客等待时间(分)',
type                int                 COMMENT'订单类型：预约|实时|等等',
start_catalog       string              COMMENT'开始地址的位置分类' ,
dest_catalog        string              COMMENT'目标地址的位置分类',
d_age               int                 COMMENT'司机年龄',
d_gender            tinyint             COMMENT'性别' ,
d_create_time       string              COMMENT'录入时间',
car_level           string              COMMENT'车况级别',
d_phone_model       int                 COMMENT'手机型号',
d_type              tinyint             COMMENT'司机类型1:加盟司机2:自营车司机3:营运司机',
d_car_brand         string              COMMENT'车辆品牌',
d_car_level         int                 COMMENT'车辆级别',
d_channel           int                 COMMENT'渠道' ,
d_work_times        double              COMMENT'入职时长_月',
d_active_degree     int                 COMMENT'活跃度',
d_complete_app      string              COMMENT'竞品APP' ,
d_finish_count      int                 COMMENT'累计完成订单数',
d_total_passenger_complaint int             COMMENT'累计被投诉次数',
d_work_day          int                 COMMENT'入职天数',
d_active_day        int                 COMMENT'上线天数',
d_average_level     double              COMMENT'司机最近100单的平均星级',
d_star_level        double              COMMENT'司机星级',
d_service_score     double              COMMENT'司机服务分，100分',
p_age               int                 COMMENT'乘客年龄',
p_gender            int                 COMMENT'乘客性别',
p_phone_model       string              COMMENT'乘客端',
p_finish_count      int                 COMMENT'完成订单数',
p_star_level        double              COMMENT'总评分',
p_finish_num1w      int                 COMMENT'最近1周订单数',
p_one_star_level_num int                 COMMENT'1星评论订单数',
p_two_star_level_num int                 COMMENT'2星评论订单数',
p_three_star_level_num int                 COMMENT'3星评论订单数',
p_four_star_level_num int                 COMMENT'4星评论订单数',
p_five_star_level_num int                 COMMENT'5星评论订单数',
p_registered_time   int                 COMMENT'乘客注册年龄',
p_complaint_orders  int                 COMMENT'乘客投诉订单一天前',
p_complaint_by_driver int                 COMMENT'乘客被投诉一天前',
p_total_cancel_orders int                 COMMENT'乘客取消订单一天前',
p_night_peak        double              COMMENT'夜间倾向'
)
PARTITIONED BY(
`year` STRING,
`month` STRING,
`day` STRING)
LOCATION 'hdfs://mycluster-tj/user/common_plat_security/data/service_security/redup_normal_info_bak'